### ISSUE TITLE
Use DSS7 profile structure to store an ensemble

### ISSUE THREAD

**Issue by ktarbet** [HydrologicEngineeringCenter/HEFS_Reader#10]
DSS7 supports 'time series profile data'.  A better DSS7 test would be to use this structure.  

This feature was designed for water temperature profile data at different depths.

**Comment by ktarbet** [comment]
The path would look like this:

```/RUSSIANNAPA/APCC1/ensemble-FLOW/01SEP2019/1HOUR/T:0212019/```

**Comment by HenryGeorgist** [comment]
I am open to the idea, we could discuss it at the Retrospective - or if you think it is achievable in the next day or two I would reasonably consider it as part of this round of testing.
