### ISSUE TITLE
HEFS_WebReader to download files

### ISSUE THREAD

**Issue by ktarbet** [HydrologicEngineeringCenter/HEFS_Reader#4]
I'm working on a web downloader, as a separate exe. 

I would like to call the method below in (HEFS_DataServiceProvider) to iterate consistently, without copying the code.  @HenryGeorgist  can you please suggest some design to re-use this method.  Can we move this method into it's own interface?

```csharp
public Interfaces.ITimeSeriesOfEnsembleLocations ReadDataset(Watersheds watershed,
 DateTime start, DateTime end, string Path)
```

**Comment by HenryGeorgist** [comment]
the IEnsembleReader interface only has one other method long ReadTimeInMilliSeconds, do you want me to separate the ReadTimeInMilliseconds into a separate interface?

**Comment by HenryGeorgist** [comment]
I refactored using a new interface called "ITimeable" this resulted in a fairly unsafe casting in program.cs in the HEFS_Converter project.
