### ISSUE TITLE
Order of Location/Ensembles

### ISSUE THREAD

**Issue by ktarbet** [HydrologicEngineeringCenter/HEFS_Reader#5]
I haven't confirmed yet.   However, we way may need an indexer  by Location["locationName"], for consistent comparison of writes/ reads.  For example in DSS we sort the catalog by locationName.  The CSV reader reads by order, where 'NVRC1' would be first, but for DSS 'APCC1' would be first.

Is this a correct assumption?

**Comment by HenryGeorgist** [comment]
I updated the WatershedForecast.Equals(object obj) method to compare based on location name.
