### ISSUE TITLE
DSSEnsembleReader is creating too many Locations

### ISSUE THREAD

**Issue by ktarbet** [HydrologicEngineeringCenter/HEFS_Reader#6]
Each path in the DSS condensed catalog is becoming a forecast  (timeSeriesofEnsembleLocations)

**Comment by HenryGeorgist** [comment]
Do you need a second set of eyes to resolve this issue?

**Comment by ktarbet** [comment]
Looks like the issue may be changes to DSSIO that may have changed the sorting.  Working in DSSIO.

**Comment by HenryGeorgist** [comment]
Status Report?

**Comment by ktarbet** [comment]
Not yet resolved.  There are extra locations,  I expected 11, but had 110.

**Comment by HenryGeorgist** [comment]
Try commit 58, I implemented AddEnsembleMember(IEnsembleMember em, int emidx, DateTime issueDate, string locationName, Enumerations.WatershedName watershedName) on TimeSeriesofEnsembleLocations this should fix the issue.

**Comment by ktarbet** [comment]
I created a branch issue6 to continue work

**Comment by ktarbet** [comment]
Here is an example/current debug message:
HEFS_Reader.Implementations.WatershedForecast Locations.Count does not match
this has 10 , and the other has 1
timeSeriesOfEnsembleLocations[0] does not match

**Comment by ktarbet** [comment]
I see a possible issue:
void IWatershedForecast.AddEnsembleMember(...)   only creates a new ensemble when _ensembles.Count ==0

I think we should create one when an ensemble for a given location does not exist.

**Comment by ktarbet** [comment]
```
Different number of members. this has 59 the other has 60
at o.Locations[6].NVRC1 ensemble does not match
timeSeriesOfEnsembleLocations[0] does not match
```

The extra member is the first one and it is empty
