### ISSUE TITLE
Crash when running HEFSConverter.exe

### ISSUE THREAD

**Issue by ktarbet** [HydrologicEngineeringCenter/HEFS_Reader#9]
```Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.                                                                                       at ztsStore(Int64* , zStructTimeSeries* , Int32 )                                                                       at DSSIO.DSSWriter.StoreTimeSeriesRegular[T](String pathName, T[] values, Int32 storageFlag, String startDate, String startTime, String units, String type) in C:\project\dotnet\DSSIO\DSSWriter.cs:line 155                                    at DSSIO.DSSWriter.Write(DSSTimeSeries ts, Boolean saveAsFloat) in C:\project\dotnet\DSSIO\DSSWriter.cs:line 43         at HEFSConverter.DssEnsembleWriter.Write(String dssFileName, ITimeSeriesOfEnsembleLocations watersheds, Boolean saveAsFloat, Int32 version)                                                                                                     at HEFSConverter.Program.Main(String[] args)                                                                                                                                                       ```

I'm trying to reproduce in a debugger.

**Comment by HenryGeorgist** [comment]
status? Is this critical to solve to finish the sprint? - does it prevent the program from running all of the time?

**Comment by ktarbet** [comment]
I think this was my mistake,. Trying a version 6 file
